// Destination: scripts/validate-build.mjs
// Changes vs original:
//   • Added bundle size budget gate (5 MB total — fails CI if exceeded)
//   • Added check for /privacy and /terms pages in dist
//   • Added check for sitemap-index.xml (auto-generated by @astrojs/sitemap)

import { access, readFile, readdir, stat } from "node:fs/promises";
import { extname, join, relative, resolve } from "node:path";
import packageMetadata from "../package.json" with { type: "json" };

const root     = resolve("dist");
const failures = [];
const htmlFiles = [];

// ── BUNDLE SIZE BUDGET ────────────────────────────────────────────────────────
// Fail the build if the total dist/ output exceeds this threshold.
// Adjust as the site grows — but require a conscious PR decision to raise it.
const BUNDLE_SIZE_BUDGET_BYTES = 5 * 1024 * 1024; // 5 MB
let totalBytes = 0;

// ── Walk dist/ ────────────────────────────────────────────────────────────────
async function walk(directory) {
  for (const name of await readdir(directory)) {
    const path    = join(directory, name);
    const details = await stat(path);
    if (details.isDirectory()) {
      await walk(path);
    } else {
      totalBytes += details.size;
      if (extname(path) === ".html") htmlFiles.push(path);
    }
  }
}

function fail(file, message) {
  failures.push(`${relative(root, file)}: ${message}`);
}

await walk(root);

// ── Bundle size check ─────────────────────────────────────────────────────────
if (totalBytes > BUNDLE_SIZE_BUDGET_BYTES) {
  failures.push(
    `bundle size: ${(totalBytes / 1024 / 1024).toFixed(2)} MB exceeds ${BUNDLE_SIZE_BUDGET_BYTES / 1024 / 1024} MB budget. ` +
    `Review recent asset additions or raise the budget in scripts/validate-build.mjs.`
  );
}

// ── Per-HTML-file checks ──────────────────────────────────────────────────────
for (const file of htmlFiles) {
  const html = await readFile(file, "utf8");

  if (!/<html\s+lang=/i.test(html))
    fail(file, "missing document language");

  if (!html.includes(`data-release="${packageMetadata.version}"`))
    fail(file, "missing or mismatched release identity");

  if (!html.includes(`name="application-version" content="${packageMetadata.version}"`))
    fail(file, "missing or mismatched application version metadata");

  if (!/<title>[^<]+<\/title>/i.test(html))
    fail(file, "missing page title");

  if (!/<meta\s+name="description"/i.test(html))
    fail(file, "missing meta description");

  if (!/<link\s+rel="canonical"/i.test(html))
    fail(file, "missing canonical URL");

  if (!/<main(?:\s|>)/i.test(html))
    fail(file, "missing main landmark");

  if (!/class="skip-link"/i.test(html))
    fail(file, "missing skip link");

  // Privacy notice check — all pages must link to /privacy/
  if (!html.includes('href="/privacy/') && !file.endsWith("privacy/index.html") && !file.endsWith("terms/index.html")) {
    fail(file, "missing privacy policy link — add to footer");
  }

  // Broken anchor check
  const ids = new Set([...html.matchAll(/\sid="([^"]+)"/g)].map(m => m[1]));
  for (const match of html.matchAll(/href="#([^"]+)"/g)) {
    if (!ids.has(match[1])) fail(file, `broken page anchor #${match[1]}`);
  }

  // Missing local asset check
  for (const match of html.matchAll(/(?:href|src)="\/(?!\/)([^"?#]+)[^"]*"/g)) {
    const target = join(root, decodeURIComponent(match[1]));
    try { await access(target); }
    catch { fail(file, `missing local asset /${match[1]}`); }
  }

  // Image alt text check
  for (const image of html.matchAll(/<img\b[^>]*>/gi)) {
    if (!/\salt="[^"]*"/i.test(image[0]))
      fail(file, "image missing alt text");
  }
}

// ── Required build artifacts ──────────────────────────────────────────────────
const required = [
  "404.html",
  "robots.txt",
  "downloads/Kranthi_Delivery_Leader.pdf",
  "privacy/index.html",      // NEW — privacy page must be built
  "terms/index.html",        // NEW — terms page must be built
];

// Accept either sitemap.xml (legacy) or sitemap-index.xml (@astrojs/sitemap)
const hasSitemap =
  await access(join(root, "sitemap-index.xml")).then(() => true).catch(() => false) ||
  await access(join(root, "sitemap.xml")).then(() => true).catch(() => false);
if (!hasSitemap) failures.push("sitemap: no sitemap.xml or sitemap-index.xml found");

for (const path of required) {
  try { await access(join(root, path)); }
  catch { failures.push(`${path}: required build artifact missing`); }
}

// ── Result ────────────────────────────────────────────────────────────────────
if (failures.length) {
  console.error(
    `\nValidation failed with ${failures.length} issue(s):\n` +
    failures.map(f => `  ✗ ${f}`).join("\n") +
    "\n"
  );
  process.exit(1);
}

console.log(
  `\n✓ Validated ${htmlFiles.length} HTML files.` +
  `\n✓ Bundle size: ${(totalBytes / 1024 / 1024).toFixed(2)} MB / ${BUNDLE_SIZE_BUDGET_BYTES / 1024 / 1024} MB budget.` +
  `\n✓ All required artifacts present.\n`
);
